# Generated by Django 4.2.7 on 2024-02-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('sl_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('date_of_join', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
