# Generated by Django 4.2.7 on 2024-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0002_alter_employeeinfo_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='last_date',
            field=models.DateField(blank=True, default='Test', null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
